daily-dir:
  runOnStartup: true
  addToFavorites: true
  removeFromFavorites: true
  createDailyDir: true
  removeOldDailyDirs: true
  removeOldDailyDirsDays: 3
  dailyDirFormat: "M-dd-yyyy"
  useCron: true
  cron: "* * * * * *"
  parentDir: "build/sandbox/daily-dir"
  favoritesDir: "build/sandbox/favorites"
